// ============================================
// 🍻 FRASES-EUNUNCA — Banco de frases do /eununca
// ============================================
// Lista de frases "Eu nunca..." em pt-BR p/ a brincadeira de grupo.
// Curadoria manual: mistura de leve, engraçado e picante (sem explícito).
// O comando sorteia uma por vez e evita repetir a mesma duas vezes
// seguidas no mesmo grupo (memória em Map, sem Mongo).
// Para adicionar frases novas, basta acrescentar strings neste array.
// ============================================

module.exports = [
  "Eu nunca fingi que estava dormindo pra não falar com ninguém.",
  "Eu nunca comi sobremesa antes do almoço.",
  "Eu nunca dormi de roupa por preguiça de trocar.",
  "Eu nunca tomei café frio porque esqueci a xícara na mesa.",
  "Eu nunca falei sozinho no carro como se fosse uma entrevista.",
  "Eu nunca dancei na frente do espelho.",
  "Eu nunca cantei no chuveiro como se fosse um show.",
  "Eu nunca ensaiei uma conversa no espelho antes de ligar pra alguém.",
  "Eu nunca comi pizza no café da manhã.",
  "Eu nunca deixei o celular descarregar por preguiça de levantar pra carregar.",
  "Eu nunca usei a mesma meia dois dias seguidos.",
  "Eu nunca dormi com a TV ligada e acordei sem saber o que passou.",
  "Eu nunca comi brigadeiro direto da panela.",
  "Eu nunca roubei a coberta de quem dormia do meu lado.",
  "Eu nunca acordei assustado com o meu próprio ronco.",
  "Eu nunca colei na prova olhando pro colega do lado.",
  "Eu nunca inventei uma desculpa pra faltar aula.",
  "Eu nunca dormi na aula e acordei assustado.",
  "Eu nunca fingi que entendi pra não ter que perguntar de novo.",
  "Eu nunca cheguei atrasado e entrei na sala de fininho.",
  "Eu nunca fiz o trabalho em grupo sozinho e coloquei o nome de todo mundo.",
  "Eu nunca mandei e-mail com erro de português pro chefe.",
  "Eu nunca fingi que estava em reunião pra não atender uma ligação.",
  "Eu nunca deixei tudo pra última hora e mesmo assim deu certo.",
  "Eu nunca apaguei uma mensagem no grupo do trabalho antes de alguém ler.",
  "Eu nunca stalkeei meu ex nas redes sociais.",
  "Eu nunca tirei print de conversa e mandei pra pessoa errada.",
  "Eu nunca mandei um áudio de 5 minutos pra dizer uma frase só.",
  "Eu nunca digitei uma mensagem e apaguei tudo antes de enviar.",
  "Eu nunca fiquei sem bateria bem no meio de uma conversa importante.",
  "Eu nunca respondi story só pra puxar assunto.",
  "Eu nunca deixei alguém no vácuo de propósito.",
  "Eu nunca visualizei mensagem e fingi que não vi.",
  "Eu nunca postei foto antiga fingindo que era de hoje.",
  "Eu nunca pesquisei o meu próprio nome no Google.",
  "Eu nunca joguei até de madrugada e me arrependi no dia seguinte.",
  "Eu nunca perdi uma partida por causa do lag e culpei a internet.",
  "Eu nunca maratonei uma série inteira num fim de semana só.",
  "Eu nunca comi miojo três dias seguidos.",
  "Eu nunca roubei batata frita do prato de alguém.",
  "Eu nunca lambi a tampa do iogurte.",
  "Eu nunca comi bolo direto da forma.",
  "Eu nunca coloquei ketchup em absolutamente tudo.",
  "Eu nunca pedi delivery mesmo tendo comida em casa.",
  "Eu nunca disse que não queria sobremesa e depois comi a dos outros.",
  "Eu nunca bebi refrigerante direto da garrafa.",
  "Eu nunca separei o biscoito recheado e comi só o recheio.",
  "Eu nunca tomei sorvete no frio.",
  "Eu nunca me perdi mesmo usando GPS.",
  "Eu nunca peguei o ônibus errado.",
  "Eu nunca dormi no transporte e passei do meu ponto.",
  "Eu nunca esqueci um documento importante em casa.",
  "Eu nunca viajei sem planejar absolutamente nada.",
  "Eu nunca cheguei no aeroporto em cima da hora.",
  "Eu nunca pedi informação e mesmo assim me perdi.",
  "Eu nunca trouxe uma lembrancinha inútil de viagem.",
  "Eu nunca falei \"amanhã eu começo a dieta\" e não comecei.",
  "Eu nunca quebrei a dieta no primeiro dia.",
  "Eu nunca prometi que ia acordar cedo e dormi até tarde.",
  "Eu nunca fiz promessa de ano novo que não cumpri.",
  "Eu nunca disse \"só mais 5 minutinhos\" e dormi mais uma hora.",
  "Eu nunca malhei janeiro inteiro e parei em fevereiro.",
  "Eu nunca tomei energético pra aguentar a noite.",
  "Eu nunca dormi de maquiagem por preguiça.",
  "Eu nunca comprei roupa que não serviu por impulso.",
  "Eu nunca fiquei horas escolhendo filme e acabei não vendo nada.",
  "Eu nunca chorei vendo filme de cachorro.",
  "Eu nunca torci pro vilão no meio do filme.",
  "Eu nunca dormi no cinema.",
  "Eu nunca saí do cinema no meio por achar o filme ruim.",
  "Eu nunca briguei com amigo por causa de jogo.",
  "Eu nunca passei vergonha num karaokê.",
  "Eu nunca cantei errado a letra de uma música famosa.",
  "Eu nunca tive uma música grudada na cabeça o dia inteiro.",
  "Eu nunca ouvi uma música em loop até enjoar.",
  "Eu nunca gravei áudio cantando e mandei pros amigos.",
  "Eu nunca fui expulso de uma partida online por xingar.",
  "Eu nunca esqueci o aniversário de alguém importante.",
  "Eu nunca dei parabéns atrasado com vergonha.",
  "Eu nunca ganhei presente que não gostei e fingi que amei.",
  "Eu nunca reaproveitei um presente que ganhei.",
  "Eu nunca coloquei apelido engraçado em alguém da agenda.",
  "Eu nunca salvei contato com emoji pra lembrar quem é.",
  "Eu nunca liguei pra pessoa errada sem querer.",
  "Eu nunca atendi ligação achando que era outra pessoa.",
  "Eu nunca mandei \"kkkk\" sem estar rindo de verdade.",
  "Eu nunca usei figurinha pra evitar responder.",
  "Eu nunca entrei num grupo só pra ler a treta.",
  "Eu nunca saí de um grupo sem me despedir e voltei depois.",
  "Eu nunca mutilei palavra no corretor e enviei errado.",
  "Eu nunca discuti com alguém por mensagem e me arrependi.",
  "Eu nunca apaguei histórico de conversa com medo de alguém ver.",
  "Eu nunca deixei o corretor me trair numa mensagem séria.",
  "Eu nunca mandei bom dia em grupo de família pra não ficar feio.",
  "Eu nunca recebi ligação de número desconhecido e não atendi.",
  "Eu nunca bloqueei alguém e desbloqueei depois.",
  "Eu nunca menti dizendo que já estava a caminho.",
  "Eu nunca cheguei atrasado num encontro.",
  "Eu nunca fui num encontro que foi bem pior que o esperado.",
  "Eu nunca inventei um compromisso pra sair mais cedo de um encontro.",
  "Eu nunca fiquei com vergonha de pedir a conta dividida.",
  "Eu nunca paquerei alguém e fui ignorado.",
  "Eu nunca mandei mensagem pra pessoa errada na hora da paquera.",
  "Eu nunca tive crush num professor ou professora.",
  "Eu nunca escrevi cartinha de amor.",
  "Eu nunca decorei o número de alguém de cor.",
  "Eu nunca sonhei com alguém que não deveria.",
  "Eu nunca fiquei nervoso só de ver alguém passar.",
  "Eu nunca treinei na frente do espelho o que ia falar pra alguém.",
  "Eu nunca revelei um segredo que não devia.",
  "Eu nunca ouvi conversa alheia fingindo que não estava ouvindo.",
  "Eu nunca espalhei uma fofoca que ouvi por aí.",
  "Eu nunca descobri uma fofoca sobre mim por terceiros.",
  "Eu nunca li o diário de alguém escondido.",
  "Eu nunca abri presente antes da hora.",
  "Eu nunca comentei spoiler sem querer.",
  "Eu nunca briguei por causa de herança de controle remoto.",
  "Eu nunca escondi comida dos irmãos.",
  "Eu nunca briguei com irmão por besteira e fiz as pazes no mesmo dia.",
  "Eu nunca fui o favorito da vovó.",
  "Eu nunca fingi estar doente pra ganhar mimo.",
  "Eu nunca quebrei algo em casa e escondi.",
  "Eu nunca derrubei o celular na cara deitado na cama.",
  "Eu nunca deixei o celular cair na privada.",
  "Eu nunca usei o celular até 1% sem carregar.",
  "Eu nunca esqueci a senha do cartão na hora de pagar.",
  "Eu nunca passei vergonha no caixa por falta de saldo.",
  "Eu nunca paguei mico no banco.",
  "Eu nunca perdi dinheiro no bolso da calça e achei depois.",
  "Eu nunca gastei tudo no começo do mês.",
  "Eu nunca comprei coisa inútil numa promoção.",
  "Eu nunca me endividei no cartão de crédito.",
  "Eu nunca fiz planilha de gastos e desisti na primeira semana.",
  "Eu nunca pedi dinheiro emprestado pros pais sendo adulto.",
  "Eu nunca achei dinheiro na rua.",
  "Eu nunca apostei com amigo e perdi.",
  "Eu nunca fiz promessa em troca de favor.",
  "Eu nunca dormi na casa de amigo sem avisar ninguém.",
  "Eu nunca fui na festa só pela comida.",
  "Eu nunca dancei até o pé doer.",
  "Eu nunca cantei parabéns desafinado.",
  "Eu nunca fui o último a ir embora da festa.",
  "Eu nunca cheguei numa festa sem conhecer ninguém.",
  "Eu nunca usei roupa repetida em duas festas seguidas.",
  "Eu nunca passei a virada do ano dormindo.",
  "Eu nunca fiz churrasco que queimou tudo.",
  "Eu nunca fui pescar e não peguei nada.",
  "Eu nunca joguei bola descalço e machuquei o dedão.",
  "Eu nunca caí da bicicleta na frente de todo mundo.",
  "Eu nunca tomei banho de chuva de propósito.",
  "Eu nunca subi numa árvore e não consegui descer.",
  "Eu nunca brinquei de esconde-esconde depois de velho.",
  "Eu nunca perdi no par ou ímpar de propósito.",
  "Eu nunca trapaceei num jogo de tabuleiro.",
  "Eu nunca perdi pro meu irmão mais novo e fiquei bravo.",
  "Eu nunca chorei perdendo videogame.",
  "Eu nunca quebrei controle de raiva.",
  "Eu nunca passei de fase depois de 50 tentativas.",
  "Eu nunca deixei o time perder por minha causa.",
  "Eu nunca comemorei gol antes da hora.",
  "Eu nunca torci contra o time do coração por birra.",
  "Eu nunca pintei o rosto pra ir no estádio.",
  "Eu nunca gritei tanto que ficou sem voz no dia seguinte.",
  "Eu nunca dormi na praia e acordei todo queimado.",
  "Eu nunca perdi o chinelo na areia.",
  "Eu nunca tomei caldo de mar.",
  "Eu nunca fiz castelo de areia depois de velho.",
  "Eu nunca fui pego pela onda de surpresa.",
  "Eu nunca esqueci protetor solar e virei camarão.",
  "Eu nunca viajei com a família e briguei no carro.",
  "Eu nunca cantei o caminho inteiro da viagem.",
  "Eu nunca pedi pra parar no banheiro 10 vezes na estrada.",
  "Eu nunca esqueci mala no hotel.",
  "Eu nunca comprei souvenir cafona.",
  "Eu nunca experimentei comida estranha em viagem.",
  "Eu nunca dormi no avião antes de decolar.",
  "Eu nunca tive medo de turbulência.",
  "Eu nunca bati palma quando o avião pousou.",
  "Eu nunca perdi o voo por 5 minutos.",
  "Eu nunca esqueci o passaporte em casa.",
  "Eu nunca tirei foto com estátua fazendo pose.",
  "Eu nunca me perdi num museu.",
  "Eu nunca entrei no lugar errado por engano.",
  "Eu nunca usei tradutor pra pedir comida fora do país.",
  "Eu nunca pedi comida apontando pro cardápio.",
  "Eu nunca provei pimenta achando que não ardia.",
  "Eu nunca chorei cortando cebola.",
  "Eu nunca queimei a comida e servi mesmo assim.",
  "Eu nunca salguei demais e fingi que estava ótimo.",
  "Eu nunca comi miojo cru como salgadinho.",
  "Eu nunca bebi leite direto da caixa.",
  "Eu nunca roubei pedaço de bolo antes de cortar.",
  "Eu nunca lambi a colher do bolo.",
  "Eu nunca fiz brigadeiro e comeu antes de enrolar.",
  "Eu nunca tomei café tão forte que não dormi.",
  "Eu nunca coloquei açúcar no lugar do sal.",
  "Eu nunca tentei cozinhar receita da internet e deu errado.",
  "Eu nunca pedi pizza porque a janta queimou.",
  "Eu nunca beijei alguém que tinha acabado de conhecer.",
  "Eu nunca tive uma ficada de uma noite só.",
  "Eu nunca usei um aplicativo de relacionamento.",
  "Eu nunca me arrependi de um beijo.",
  "Eu nunca menti sobre minha idade pra flertar.",
  "Eu nunca dei um número de telefone falso.",
  "Eu nunca fui a um encontro às cegas.",
  "Eu nunca terminei com alguém por mensagem ou pelas redes sociais.",
  "Eu nunca estive na friendzone.",
  "Eu nunca dei em cima de alguém atendendo no bar ou restaurante na cara dura.",
  "Eu nunca tive um encontro que terminou em menos de 30 minutos.",
  "Eu nunca tomei a iniciativa de forma bem direta.",
  "Eu nunca disse eu te amo primeiro.",
  "Eu nunca fiquei de coração partido a ponto de não querer sair da cama.",
  "Eu nunca dei um beijão memorável na chuva igual nos filmes.",
  "Eu nunca chamei alguém pra minha casa na primeira noite.",
  "Eu nunca tive um encontro que deu completamente errado por causa de bebida.",
  "Eu nunca fiz uma declaração de amor em público.",
  "Eu nunca menti dizendo que já estava a caminho de um encontro.",
  "Eu nunca cheguei atrasado num encontro importante.",
  "Eu nunca inventei um compromisso pra sair mais cedo de um encontro ruim.",
  "Eu nunca tive um crush num professor ou professora.",
  "Eu nunca usei um aplicativo de relacionamento (Tinder, Bumble, etc.).",
  "Eu nunca dei beijo de língua em mais de duas pessoas na mesma noite.",
  "Eu nunca stalkeei um(a) ex de forma obsessiva.",
  "Eu nunca tive uma fantasia com o(a) melhor amigo(a) do(a) meu/minha parceiro(a).",
  "Eu nunca estive na \"friendzone\".",
  "Eu nunca fui a pessoa que tirou alguém da \"friendzone\".",
  "Eu nunca dei em cima do(a) garçom/garçonete ou barman/barwoman na cara dura.",
  "Eu nunca tive um apelido safadinho dado por um(a) parceiro(a).",
  "Eu nunca disse \"eu te amo\" primeiro.",
  "Eu nunca dei um beijão memorável na chuva (igual nos filmes!).",
  "Eu nunca menti sobre minhas intenções (procurar algo sério vs. só diversão).",
  "Eu nunca senti atração por alguém que eu definitivamente não deveria (tipo o/a parceiro(a) de alguém próximo).",
  "Eu nunca mandei uma foto pelado(a) ou de lingerie (\"nude\").",
  "Eu nunca recebi um \"nude\" sem ter pedido.",
  "Eu nunca fiz sexo em um lugar público (carro, parque, praia, banheiro...).",
  "Eu nunca fui pego(a) no flagra durante o sexo. O maior climão!",
  "Eu nunca entrei para o \"mile high club\" (fazer sexo em um avião).",
  "Eu nunca fiz sexo na água (piscina, mar, jacuzzi...).",
  "Eu nunca fiz sexo em um lugar bem arriscado (escritório, elevador, provador de loja...).",
  "Eu nunca usei comida durante as preliminares ou o ato (chantilly, chocolate...).",
  "Eu nunca comprei brinquedos sexuais (\"sextoys\").",
  "Eu nunca dei um nome para um dos meus sextoys.",
  "Eu nunca tentei bondage (mesmo que de leve, com um cachecol ou algo do tipo).",
  "Eu nunca usei algemas (ou algo parecido).",
  "Eu nunca dei ou recebi um tapa na bunda (com consentimento, óbvio!).",
  "Eu nunca fiz um strip-tease (mesmo que de brincadeira ou se foi um desastre).",
  "Eu nunca transei por mais de 3 horas seguidas.",
  "Eu nunca filmei ou tirei foto do ato (mesmo que tenha apagado depois).",
  "Eu nunca assisti a um filme pornô com um(a) parceiro(a).",
  "Eu nunca assisti a um filme pornô sozinho(a).",
  "Eu nunca me machuquei (mesmo que de leve) durante uma atividade sexual.",
  "Eu nunca testei uma posição do Kama Sutra particularmente acrobática.",
  "Eu nunca tive um orgasmo tão barulhento que os vizinhos devem ter ouvido.",
  "Eu nunca fingi um orgasmo.",
  "Eu nunca tive uma experiência homossexual (se geralmente sou hétero) ou heterossexual (se geralmente sou homo/bi).",
  "Eu nunca fiz sexo sob o efeito de drogas (além de álcool).",
  "Eu nunca tive medo de ter pego uma IST depois de uma relação sem proteção. (Lembrete: usem camisinha!)",
  "Eu nunca fui infiel fisicamente.",
  "Eu nunca fui infiel emocionalmente (desenvolver sentimentos fortes por outra pessoa).",
  "Eu nunca perdoei uma traição.",
  "Eu nunca fui a pessoa com quem alguém traiu seu/sua parceiro(a) (o/a amante).",
  "Eu nunca tive um relacionamento secreto que ninguém (ou quase ninguém) sabia.",
  "Eu nunca tive uma \"amizade colorida\".",
  "Eu nunca desenvolvi sentimentos pelo(a) meu/minha \"amigo(a) colorido(a)\".",
  "Eu nunca tive um relacionamento puramente baseado em sexo.",
  "Eu nunca espionei o celular, as mensagens ou as redes sociais do(a) meu/minha parceiro(a).",
  "Eu nunca senti ciúmes a ponto de fazer uma cena.",
  "Eu nunca menti sobre meu status de relacionamento (dizer que estava solteiro(a) quando não estava, ou o contrário).",
  "Eu nunca tive um relacionamento à distância.",
  "Eu nunca tive um relacionamento com alguém que conheci online sem nunca ter visto pessoalmente.",
  "Eu nunca me relacionei com alguém muito mais velho (+10 anos).",
  "Eu nunca me relacionei com alguém muito mais novo (-10 anos).",
  "Eu nunca participei de um ménage à trois (ou com mais gente...).",
  "Eu nunca participei de uma festa de swing ou liberal.",
  "Eu nunca me relacionei com meu/minha chefe ou um(a) colega de trabalho direto(a).",
  "Eu nunca fiquei com o(a) irmão/irmã de um(a) amigo(a).",
  "Eu nunca fiquei com o(a) colega de quarto do(a) meu/minha parceiro(a).",
  "Eu nunca escondi do(a) meu/minha parceiro(a) atual um relacionamento importante do passado.",
  "Eu nunca me arrependi de ter terminado um relacionamento.",
  "Eu nunca fiz um barraco em público com meu/minha parceiro(a).",
  "Eu nunca paguei por sexo.",
  "Eu nunca recebi dinheiro por sexo.",
  "Eu nunca tive uma fantasia com uma celebridade específica (mesmo que muito improvável).",
  "Eu nunca sonhei em transar em um lugar muito específico (e muito original).",
  "Eu nunca tive uma obsessão temporária por uma pessoa que eu nem conhecia direito.",
  "Eu nunca digitei \"como saber se sinto atração por...\" no Google.",
  "Eu nunca fiquei excitado(a) com uma cena de filme que não era pra ser sexy.",
  "Eu nunca imaginei uma cena sexy com uma pessoa que eu provavelmente nunca mais veria.",
  "Eu nunca tive um crush completamente sem noção (professor, chefe, desconhecido do metrô...).",
  "Eu nunca realizei uma fantasia sozinho(a) sem nunca ter coragem de contar pra ninguém.",
  "Eu nunca senti atração por alguém só pela voz.",
  "Eu nunca quis reviver um momento íntimo específico só \"pra ver como é\".",
  "Eu nunca fingi timidez quando na verdade eu estava super a fim.",
  "Eu nunca explorei um fetiche ou \"kink\" específico (mesmo que só online).",
  "Eu nunca tive curiosidade sobre uma prática tabu (sem necessariamente ter testado).",
  "Eu nunca imaginei um \"cenário proibido\" só pela zoeira (sem nunca fazer de verdade).",
  "Eu nunca tive medo de confessar uma fantasia para meu/minha parceiro(a).",
  "Eu nunca tive um sonho tão intenso que não contei pra ninguém.",
  "Eu nunca usei uma fanfic ou um texto pra me excitar.",
  "Eu nunca procurei o significado de um termo sexual que eu não conhecia.",
  "Eu nunca tive uma fantasia com um(a) desconhecido(a) que vi uma única vez.",
  "Eu nunca imaginei uma \"outra vida\" amorosa ou sexual com alguém.",
  "Eu nunca fiquei excitado(a) lendo um texto ou um livro (e não só um filme ou vídeo).",
  "Eu nunca senti vontade de fazer um ménage, mesmo que só na teoria.",
  "Eu nunca guardei um segredo sexual que não pretendo confessar nunca.",
  "Eu nunca tive um pensamento sexual completamente sem noção (e assumi isso).",
  "Eu nunca me surpreendi com o que realmente me excita."
]
