// ============================================
// 🎭 PERGUNTAS-VOUC — Banco do /verdadeouconsequencia
// ============================================
// Duas listas separadas (curadoria manual), em pt-BR:
//   VERDADES  → perguntas pra responder honestamente;
//   DESAFIOS → ações pra fazer na hora, no próprio grupo.
//
// Tom: brincadeira de grupo, do leve ao mais ousado. Nada ofensivo, nada
// sexual explícito e nada que dependa do corpo ou da intimidade de terceiros:
// a graça é responder e medir a cara, nao constranger alguem de verdade.
//
// O comando sorteia UMA por chamada, SEM estado persistente (nada de Mongo nem
// de bloqueio via jogos-ativos.js — nao existe rodada em andamento). A unica
// memoria e a trava diaria deterministica, que nunca repete a mesma pergunta
// pra mesma pessoa no mesmo dia. Ver a documentacao em:
//   comandos/menu-brincadeiras/verdadeouconsequencia.js
//
// Para adicionar perguntas novas, basta acrescentar strings no array.
// ============================================

module.exports = {
  // ── 🎭 VERDADES (perguntas) ──
  VERDADES: [
    "Qual foi a coisa mais boba que voce ja fez num grupo de amigos?",
    "Se voce pudesse trocar de corpo com qualquer pessoa daqui por um dia, quem seria?",
    "Qual e o seu pior habito?",
    "Qual musica te faz vergonha alheia?",
    "Qual foi a desculpa mais criativa que voce ja deu pra chegar atrasado?",
    "Que superpoder inutil voce escolheria?",
    "Qual foi a compra mais burra que voce ja fez sem pensar?",
    "Se as pessoas pudessem ver um status seu hoje, o que ele diria?",
    "Qual foi o presente mais sem vergonha que voce ja deu?",
    "Qual foi o momento mais constrangedor da sua vida escolar?",
    "Qual e a sua marca registrada quando aparece numa festa?",
    "Qual foi a ultima coisa que te fez rir sozinho no celular?",
    "Se voce pudesse banir uma palavra do mundo, qual seria?",
    "Qual e a coisa que voce faz mal e continua fazendo mesmo assim?",
    "Qual foi a maior mentira que voce ja contou pra alguem acreditar?",
    "Que mania sua as pessoas fingem que nao tem?",
    "Qual habito do outro voce nao suporta mas finge que suporta?",
    "Que frase famosa voce sempre quis ter dito, mas nunca disse?",
    "Qual foi o erro mais bobo que voce ja mandou numa conversa de trabalho?",
    "Qual e o tipo de pessoa que te da mais preguiça de lidar?",
    "Qual foi a maior fofoca que voce ja contou e se arrependeu depois?",
    "Voce ja mandou um kkkk e queria que fosse um tchau?",
    "Qual e a coisa mais brega que voce gosta?",
    "Se voce fosse personagem de novela, qual seria?",
    "Qual foi o momento em que voce mais quis sumir de um lugar?",
    "Qual qualidade sua as pessoas mais proximas ainda nao descobriram?",
    "Voce tem alguma mania que esconde de todo mundo?",
    "Qual foi a desculpa mais maluca pra nao pagar uma conta?",
    "Qual foi o momento em que voce mais se sentiu um impostor?",
    "Qual e o hobby que voce esconde das pessoas?",
    "Voce ja mandou mensagem no grupo errado? Conta sem querer?",
    "Qual foi a coisa mais fofa que voce ja fez e se arrependeu logo depois?",
    "Qual musica voce associa a uma memoria constrangedora?",
    "Se voce pudesse apagar uma memoria sua, qual seria?",
    "Qual e a sua desculpa favorita pra nao sair do pijama?",
    "Qual foi a maior coisa bobinha que voce ja gastou dinheiro a toa?",
    "Qual capacidade sua voce superestima um pouquinho?",
    "Qual e o segredo inofensivo que voce ja guardou por anos?",
    "Qual foi o maior arrependimento de um dia esquentado?",
    "Qual foi a coisa mais brega que voce ja usou?",
    "Que talentinho bobo voce tem e esconde de todo mundo?",
    "Qual foi a maior mentira do tipo eu tambem fui que voce ja contou?",
    "Se o grupo te desse um superpoder inutil, o que voce pediria?",
    "Qual foi a frase que voce repetiu do professor sem entender nada?",
    "Voce ja falou mal de alguem que estava do outro lado da tela?",
    "Qual e a coisa que voce faz quando ta muito triste e nao conta pra ninguem?",
    "Qual foi o lugar mais estranho onde voce ja dormiu?",
    "Voce ja se enrolou numa historia so pra se livrar de uma bronca?",
    "Qual e o medo bobo que voce nunca assume ter?",
    "Qual foi a maior bagunca da sua vida que virou comedia depois?",
    "Que mania de comida voce tem e esconde das pessoas?",
    "Qual foi a vez que voce se fez de doido pra nao fazer algo?",
    "Voce ja chegou num lugar e fingiu que era outro?",
    "Qual e a mentirazinha boba que voce sempre conta?",
    "Qual foi a coisa mais infantil que voce fez com toda seriedade?",
    "Qual foi a pior prova que voce ja fez na vida?",
    "Que mania sua as pessoas adoram e voce faz sem entender o motivo?",
    "Qual foi a vez que voce chegou no trabalho de madrugada e fingiu que estava tudo bem?",
    "Qual foi o maior susto que voce ja levou por causa de boba?",
    "Se voce pudesse viajar no tempo uma vez, pra quando ir?",
    "Qual e a coisa que voce faz quando ta nervoso?",
    "Voce ja cheirou algo estranho e fingiu que nao?",
    "Qual foi a decisao mais burra que voce ja tomou com conviccao?",
    "Qual e a parte do seu dia que voce mais finge que aguenta?",
    "Voce ja bloqueou alguem e depois voltou a falar com essa pessoa?",
    "Qual foi a frase que voce inventou pra sair de uma conversa?",
    "Qual e o que voce mais esconde das pessoas perto de voce?",
    "Qual foi a vez que voce fingiu estar ocupado pra nao falar com alguem?",
    "Voce ja se perdeu no seu proprio bairro?",
    "Qual foi a coisa mais brega que voce tem na carteira?",
    "Qual e a razao pela qual voce nunca sai de casa num domingo?",
    "Qual foi o maior medo de infancia que voce ainda tem um pouquinho?",
    "Voce ja mandou audio longo demais pra um assunto simples?",
    "Qual foi a hora que voce mais gostou de ficar sem fazer nada?",
    "Qual e a mania que voce tem com comida e nunca contou pra ninguem?",
    "Voce ja contou um segredo que prometeu guardar?",
    "Qual foi a coisa mais estranha que voce ja viu numa rua?",
    "Qual e o horario do dia em que voce fica mais lento?",
    "Voce ja saiu de manha pra trabalhar e voltaste a noite do mesmo dia?",
    "Qual foi a promessa que voce ja fez e esqueceu de cumprir?",
    "Qual e o filme que voce finge que gosta so porque todo mundo gosta?",
    "Voce ja entrou no cinema errado e ficou mesmo assim?",
    "Qual foi a coisinha boba que voce comprou porque era linda e nunca usou?",
    "Qual e a coisa que voce faria se ninguem pudesse te julgar?",
    "Voce ja fingiu que estava dormindo pra nao participar de uma reuniao?",
    "Qual foi a maior zoeira que voce ja levou e fingiu que nao ligou?",
    "Qual e o lugar da casa que voce mais gosta?",
    "Voce ja passou vergonha na frente de alguem que voce respeita muito?",
    "Qual e a coisa que voce faz quando quer muito sair de um lugar?",
    "Voce ja mandou mensagem no grupo errado contando um segredo?",
    "Qual foi o apelido mais sem vergonha que voce ja ganhou?",
    "Voce ja fez chantagem por brincadeira e se arrependeu?",
    "Qual e a coisa mais cara que voce ja destruiu sem querer?",
    "Voce ja deu um presente ruim e teve que dar outro depois?",
    "Qual e a memoria mais ridicula que voce tem da escola?",
    "Voce ja se sentiu um impostor na faculdade ou no trabalho?",
    "Qual e a coisa mais brega do seu quarto ou apartamento?",
    "Voce ja tentou responder um audio e desistiu no caminho?",
    "Qual foi a maior dor de cabeca que voce ja teve por causa de boba?",
    "Qual e a coisa mais esquisita que voce carrega na bolsa ou mochila?",
    "Voce ja mandou mensagem pra pessoa errada e fingiu que nao foi?",
    "Qual e o pedido que voce faz e nunca se sente culpado?",
    "Voce ja escorregou ou caiu de um jeito ridiculo na frente de alguem?",
    "Qual e a coisa mais improvisada que voce ja fez e deu certo?",
    "Voce ja tentou aprender algo por video e desistiu no primeiro dia?",
    "Qual e a mentira mais boba que voce conta e ninguem questiona?",
    "Voce ja deu migue pra alguem e o seu tambem?",
    "Qual e a coisa que voce faz quando fica ansioso e precisa esconder?",
    "Voce ja saiu de casa sem saber pra onde e virou uma historia boa?",
    "Qual e a desculpa mais sem vergonha que voce ja deu?",
    "Voce ja respondeu um audio com audio sem pensar?",
    "Qual e a coisa mais esquisita que voce ja comeu por coragem?",
    "Voce ja se interessou por alguem e fingiu que nao?",
    "Qual e o lugar escuro que voce nunca passearia?",
    "Voce ja cantou junto com a musica errada?",
    "Qual e a coisa mais preguiçosa que voce ja fez?",
    "Qual foi a coisa mais brega que voce ja fez e nunca contou pra ninguem?",
    "Qual e a parte mais boba da sua rotina diaria?",
    "Voce ja ficou sem reagir e depois se arrependeu?",
    "Qual e a coisa que voce faria hoje se ninguem fosse te julgar?",
    "Qual foi a maior travessura que voce ja aprontou?",
    "Voce ja mandou um emoji errado e travou a conversa?",
    "Qual e a coisa que voce mais finge que entende mas nao entende?",
    "Qual foi a vez que voce se perdeu no tempo e esqueceu o que ia falar?",


  ],

  // ── 💣 DESAFIOS (acoes pra fazer na hora, no proprio grupo) ──
  DESAFIOS: [
    "Fale a proxima frase com a voz de um personagem de desenho animado.",
    "Mande um audio de 10 segundos cantando o hino nacional.",
    "Escreva um poema de 4 versos sobre o ultimo grupo de amigos que voce frequentou.",
    "Faca um discurso de agradecimento para o grupo inteiro, bem dramatico.",
    "Conte o final de um filme de terror a seu jeito, sem spoiler.",
    "Fale em voz alta o nome de uma pessoa que nao esta no grupo.",
    "Mande uma foto de um objeto aleatorio e explique a historia dele.",
    "Faca uma imitação de alguem do grupo sem nomear.",
    "Conte uma fofoca (inofensiva) que voce ouviu essa semana.",
    "Escreva uma carta de 3 linhas para o seu eu do futuro.",
    "Fale rapido por 15 segundos sem respirar.",
    "Descreva o que voce comeria se nao tivesse limite.",
    "Faca um resumo do seu dia em uma frase, sem mentir.",
    "Mande um emoji que representa voce e explique o motivo.",
    "Imite um anuncio de TV usando o nome de alguem do grupo.",
    "Diga um nome ficticio e conte a historia dele em 30 segundos.",
    "Faca um pedido de desculpas publico (brincalhao) para alguem do grupo.",
    "Cante os primeiros 20 segundos de uma musica a sua escolha.",
    "Fale seu nome 10 vezes em voz alta bem rapido.",
    "Descreva a pessoa mais nova do grupo sem dizer o nome.",
    "Faca uma parodia de um reels que voce ja viu.",
    "Conte a historia de como voce conheceu a melhor pessoa que voce tem.",
    "Fale uma frase em outro idioma e deixe o grupo adivinhar.",
    "Faca um som de aplausos usando a boca e deixe o grupo adivinhar.",
    "Diga o nome de 5 coisas que tem no seu armario agora.",
    "Escreva um miniconto de terror em 5 linhas.",
    "Fale sem parar por 20 segundos sobre comida.",
    "Faca uma imitação de comercial de margarina.",
    "Descreva a si mesmo como se fosse um personagem de RPG.",
    "Mande uma foto da sua tela agora (sem printar nada privado, claro).",
    "Conte uma piada de papai noel ou de mae que te fez rir.",
    "Fale o nome de 3 musicas que te fazem lembrar de alguem.",
    "Descreva o dia perfeito pra voce, do começo ao fim.",
    "Faca uma encenação de 1 minuto usando emojis.",
    "Diga o que voce faria se ganhasse um milhao agora.",
    "Imite a voz de uma pessoa conhecida pelo grupo (sem nomear).",
    "Conte a coisa mais legal que voce ja aprendeu ultimamente.",
    "Escreva uma mensagem de ''bom dia'' em 5 estilos diferentes.",
    "Faca um som de animal e o grupo tem que adivinhar em 3 tentativas.",
    "Fale por 30 segundos sem usar a letra E.",
    "Descreva a comida preferida de cada pessoa do grupo (sem errar nenhuma).",
    "Faca uma parodia de propaganda de banco.",
    "Conte a historia de um objeto seu como se fosse lendaria.",
    "Mande um audio com a sua melhor imitacao de som de animal.",
    "Fale o nome de todos que tao online agora, um por um.",
    "Escreva 3 frases que comecem com a mesma letra.",
    "Faca um resumo do ultimo filme que voce viu, em 1 frase.",
    "Diga qual e a sua hobby mais estranha e explique.",
    "Fale com a voz de personagem de desenho que todo mundo conhece.",
    "Escreva um poema de 4 linhas sobre o que voce comeu no cafe da manha.",
    "Faca um reels de 5 segundos usando o que tiver ao seu redor.",
    "Descreva a foto do seu perfil como se fosse um trailer de filme.",
    "Mande a letra de uma musica que todo mundo aqui conhece.",
    "Conte uma historia de terror de 3 frases com o nome de alguem do grupo.",
    "Fale em ingles uma frase e depois em portugues, sem travar.",
    "Mande o nome do seu personagem favorito em jogos.",
    "Escreva um pedido de desculpas falso e bem dramatico pro grupo.",
    "Fale o seu signo e justifique com um fato da sua vida.",
    "Descreva o ultimo lugar que voce viajou como se fosse um Baudelaire.",
    "Mande um emoji que te representa e explique em 1 frase.",
    "Faca uma declaracao de amor pra um objeto da sua casa.",
    "Fale o nome do app que voce mais usa e imite o som de notificacao.",
    "Conte um boato do grupo como se fosse materia de jornal.",
    "Faca um resumo do seu dia em 3 palavras.",
    "Imite a voz de uma pessoa conhecida e o grupo tem que adivinhar.",
    "Mande a sua definicao de amor em uma frase curta.",
    "Descreva o seu dia de trabalho como se fosse um relatorio.",
    "Fale o nome do ultimo livro que voce leu e uma frase dele.",
    "Escreva um mini dialogo entre voce e o bot aqui.",
    "Mande um conselho ultimo em tom de avo.",
    "Fale uma verdade sobre voce que so sabiam 3 pessoas aqui.",
    "Descreva sua musica favorita como se fosse uma comida.",
    "Faca uma lista de 3 coisas que voce faria com dinheiro infinito.",
    "Conte como seria o seu casamento ideal, em detalhe.",
    "Fale quem e a pessoa mais corajosa que voce conhece e por que.",
    "Mande a sua frase de efeito favorita.",
    "Escreva um titulo de filme sobre a sua vida.",
    "Faca uma propaganda do seu produto imaginario.",
    "Descreva seu dia de folga ideal em 3 frases.",
    "Mande o nome do seu heroi (real ou ficticio) e o por que.",
    "Descreva a sua comida preferida e o sabor dela.",
    "Escreva um muro de recados usando 3 palavras repetidas.",
    "Imite um comercial de TV com o que tem ao seu redor.",
    "Fale qual seria o seu nome de artista se voce fosse famoso.",
    "Descreva a sua rotina matinal em uma frase.",
    "Mande a palavra mais longa que voce sabe de cor.",
    "Fale um conselho que voce ignorou e se arrependeu.",
    "Faca um resumo do seu ano em ate 3 emojis.",
    "Conte o melhor presente que voce ja recebeu e por que.",
    "Fale o nome do seu lugar tranquilo favorito pra ir.",
    "Descreva seu estilo de roupa em 1 frase engraçada.",
    "Mande uma piada curta sobre o dia da semana.",
    "Fale qual e a sua regra inegociavel em qualquer situacao.",
    "Descreva a sua advertencia como se fosse a previsao do tempo.",
    "Mande o nome do seu professor, chefe ou lider e uma frase de conselho.",
    "Fale qual e a sua meta do ano em 1 frase motivacional.",
    "Descreva seu lado humano como se fosse uma ficha de cadastro.",
    "Fale qual e o seu talento inutil mas que voce tem orgulho.",
    "Mande o nome do som que te faz lembrar de infancia.",
    "Descreva a sua ultima compra online como se fosse uma reliquia perdida.",
    "Fale um proverbio antigo e explique com as suas palavras.",
  ]
}
