module.exports = [
  'Quem é mais provável de dormir numa reunião?',
  'Quem é mais provável de esquecer onde deixou o celular?',
  'Quem é mais provável de virar amigo de um desconhecido na fila?',
  'Quem é mais provável de adotar todos os animais da rua?',
  'Quem é mais provável de rir numa hora séria?',
  'Quem é mais provável de levar lanche para uma viagem curta?',
  'Quem é mais provável de chegar cedo demais a uma festa?',
  'Quem é mais provável de maratonar uma série numa noite?',
  'Quem é mais provável de inventar uma receita que dá certo?',
  'Quem é mais provável de cantar no ônibus?',
  'Quem é mais provável de conhecer uma curiosidade sobre tudo?',
  'Quem é mais provável de perder a hora jogando?',
  'Quem é mais provável de organizar uma viagem surpresa?',
  'Quem é mais provável de decorar a letra de todas as músicas?',
  'Quem é mais provável de transformar um passeio em aventura?',
  'Quem é mais provável de esquecer o guarda-chuva em dia de chuva?',
  'Quem é mais provável de conversar com as plantas?',
  'Quem é mais provável de comprar um livro pela capa?',
  'Quem é mais provável de resolver um problema com uma planilha?',
  'Quem é mais provável de aprender um idioma por diversão?',
  'Quem é mais provável de dormir durante um filme de ação?',
  'Quem é mais provável de mandar um áudio de dez minutos?',
  'Quem é mais provável de guardar ingressos como lembrança?',
  'Quem é mais provável de ganhar um concurso de fantasia?',
  'Quem é mais provável de criar um apelido para todo mundo?',
  'Quem é mais provável de encontrar dinheiro numa roupa antiga?',
  'Quem é mais provável de esquecer o próprio aniversário?',
  'Quem é mais provável de contar uma história com muitos detalhes?',
  'Quem é mais provável de virar guia turístico do grupo?',
  'Quem é mais provável de fazer amizade com o garçom?',
  'Quem é mais provável de tirar cem fotos do pôr do sol?',
  'Quem é mais provável de rir da própria piada antes de terminar?',
  'Quem é mais provável de construir uma cabana numa trilha?',
  'Quem é mais provável de decorar a casa para toda comemoração?',
  'Quem é mais provável de ter um plano para um apocalipse zumbi?',
  'Quem é mais provável de encontrar um novo hobby toda semana?',
  'Quem é mais provável de esquecer a senha que acabou de criar?',
  'Quem é mais provável de escolher o restaurante pela sobremesa?',
  'Quem é mais provável de fazer uma playlist para cada ocasião?',
  'Quem é mais provável de ganhar no karaokê?',
  'Quem é mais provável de levar um jogo de tabuleiro para a praia?',
  'Quem é mais provável de saber imitar um personagem?',
  'Quem é mais provável de acordar com uma ideia genial?',
  'Quem é mais provável de procurar os óculos enquanto está usando?',
  'Quem é mais provável de lembrar o aniversário de todo mundo?'
]
